apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc2
  name: svc2
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: svc2
  type: LoadBalancer
status:
  loadBalancer: {}
